# Generated by Django 5.1 on 2024-08-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_id_number', models.CharField(max_length=20)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='orphan_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255)),
                ('sponsorship_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.ImageField(upload_to='sponsorship_receipts/')),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphans.orphan')),
            ],
        ),
    ]
