# Generated by Django 5.1 on 2024-08-10 18:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الإسم رباعي'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='guardian_id_number',
            field=models.CharField(max_length=20, verbose_name='هوية الوصي'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='guardian_name',
            field=models.CharField(max_length=255, verbose_name='اسم الوصي'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='guardian_phone',
            field=models.CharField(max_length=20, verbose_name='جوال الوصي'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='id_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='orphan_photos/', verbose_name='صورة اليتيم'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الكفالة'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='orphan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphans.orphan', verbose_name='اختر يتيم'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='receipt_image',
            field=models.ImageField(upload_to='sponsorship_receipts/', verbose_name='صورة الإستلام للكفالة'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsor_name',
            field=models.CharField(max_length=255, verbose_name='اسم الجهة الكافلة'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsorship_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ الكفالة'),
        ),
    ]
