# Generated by Django 5.1 on 2024-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0002_alter_orphan_date_of_birth_alter_orphan_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='guardian_phone',
            field=models.CharField(max_length=30, verbose_name='جوال الوصي'),
        ),
    ]
