# Generated by Django 5.1 on 2024-08-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0003_alter_orphan_guardian_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=320, max_digits=10, verbose_name='قيمة الكفالة'),
        ),
    ]
