# Generated by Django 5.1 on 2024-09-01 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0004_alter_sponsorship_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_id_number', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='archived_orphan_photos/')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedSponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphans.archivedorphan')),
            ],
        ),
    ]
