# Generated by Django 5.1 on 2024-09-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0005_archivedorphan_archivedsponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedsponsorship',
            name='sponsor_name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم الجهة الكافلة'),
            preserve_default=False,
        ),
    ]
