# Generated by Django 5.1 on 2024-09-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0006_archivedsponsorship_sponsor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10, verbose_name='قيمة الكفالة'),
        ),
    ]
