# Generated by Django 5.1 on 2024-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0007_alter_sponsorship_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='sponsorship_receipts/', verbose_name='صورة الإستلام للكفالة'),
        ),
    ]
