# Generated by Django 4.2.4 on 2025-04-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0016_alter_sponsorship_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='orphan',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='orphans.orphan', verbose_name='اختر يتيم'),
        ),
    ]
